# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-31 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectionServer', '0003_auto_20170727_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='SBT',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
